name: learn-github-actions
on: [push]
jobs: 
  check_bats-version:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install -g bats
      - run: bats -v